export const AUTH_REGISTER_REQUEST: 'AUTH_REGISTER_REQUEST' = 'AUTH_REGISTER_REQUEST';
export const AUTH_REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS' = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_ERROR: 'AUTH_REGISTER_ERROR' = 'AUTH_REGISTER_ERROR';

export const AUTH_LOGIN_REQUEST: 'AUTH_LOGIN_REQUEST' = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS' = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_ERROR: 'AUTH_LOGIN_ERROR' = 'AUTH_LOGIN_ERROR';

export const AUTH_LOGOUT_REQUEST: 'AUTH_LOGOUT_REQUEST' = 'AUTH_LOGOUT_REQUEST';
export const AUTH_LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS' = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_ERROR: 'AUTH_LOGOUT_ERROR' = 'AUTH_LOGOUT_ERROR';

export const FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST' = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS' = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR: 'FORGOT_PASSWORD_ERROR' = 'FORGOT_PASSWORD_ERROR';

export const RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST' = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS' = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR: 'RESET_PASSWORD_ERROR' = 'RESET_PASSWORD_ERROR';

export const GET_USER_REQUEST: 'GET_USER_REQUEST' = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS: 'GET_USER_SUCCESS' = 'GET_USER_SUCCESS';
export const GET_USER_ERROR: 'GET_USER_ERROR' = 'GET_USER_ERROR';

export const UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST' = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS' = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR: 'UPDATE_USER_ERROR' = 'UPDATE_USER_ERROR';